// <auto-generated />
using ChronosDTN.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChronosDTN.Infrastructure.Migrations
{
    [DbContext(typeof(ChronosDtnDbContext))]
    [Migration("20260527214127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ChronosDTN.Domain.Entities.AuditedTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ACAO");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("DETALHES");

                    b.Property<long>("OperatorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OPERADORA_ID");

                    b.Property<long>("PackageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PACOTE_ID");

                    b.Property<long>("TimestampUs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DATA_HORA");

                    b.HasKey("Id");

                    b.ToTable("TRANSACOES_AUDITADAS", (string)null);
                });

            modelBuilder.Entity("ChronosDTN.Domain.Entities.DtnPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<long>("CreationTimeUs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<long>("DestinationNodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NO_DESTINO_ID");

                    b.Property<long>("ExpirationTimeUs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DATA_EXPIRACAO");

                    b.Property<long>("OperatorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OPERADORA_ID");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PAYLOAD");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TAMANHO");

                    b.Property<long>("SourceNodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NO_ORIGEM_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("FILA_PACOTES_DTN", (string)null);
                });

            modelBuilder.Entity("ChronosDTN.Domain.Entities.Operator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("OPERADORAS_AERO", (string)null);
                });

            modelBuilder.Entity("ChronosDTN.Domain.Entities.SatelliteNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<long>("CreatedAtUs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ENDERECO_IP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PORTA");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("STATUS");

                    b.Property<long>("UpdatedAtUs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ATUALIZADO_EM");

                    b.HasKey("Id");

                    b.ToTable("NOS_SATELLITES", (string)null);
                });

            modelBuilder.Entity("ChronosDTN.Domain.Entities.DtnPackage", b =>
                {
                    b.HasOne("ChronosDTN.Domain.Entities.Operator", "Operator")
                        .WithMany("DtnPackages")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("ChronosDTN.Domain.Entities.Operator", b =>
                {
                    b.Navigation("DtnPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
